#pragma once
#include <stdint.h>
typedef enum {
    BSP_INPUT_NAVIGATION_KEY_NONE,
    BSP_INPUT_NAVIGATION_KEY_ESC,
    BSP_INPUT_NAVIGATION_KEY_LEFT,
    BSP_INPUT_NAVIGATION_KEY_RIGHT,
    BSP_INPUT_NAVIGATION_KEY_UP,
    BSP_INPUT_NAVIGATION_KEY_DOWN,
    BSP_INPUT_NAVIGATION_KEY_RETURN,
    BSP_INPUT_NAVIGATION_KEY_F1,
} bsp_input_navigation_key_t;
#define BSP_INPUT_MODIFIER_SHIFT 0x6
